---


kind: pipeline
type: docker
name: Lint/test check and Trufflehog
    
steps:

- name : Change github status
  image: python:2.7-alpine
  api_key:
    from_secret: API_KEY
  commands:
    - curl --request POST --url https://api.github.com/repos/ParasJain-dev/git_hook_test/statuses/c319f18d9e8f012ea0ba1bbcb7ede8dbe3cad3ef --header 'Authorization: token $API_KEY' --header 'Content-Type: application/json' --header 'Postman-Token: 0dbe971e-8e01-41be-a431-2e32ab10468b,13afb916-df0c-43dd-9c57-7d08d190a7cf' --header 'cache-control: no-cache' --data '{\n  "state": "success",\n  "target_url": "https://example.com/build/status",\n  "description": "The build succeeded!",\n  "context": "continuous-integration/jenkins"\n}'
  when:
    trigger:
    - pull_request
    
- name : Truffle-hog clone  
  image: docker:git
  commands:    
     - git clone https://github.com/moengage/moe-truffleHog.git --branch dev
  when:
    trigger:
    - pull_request
    
- name: Run truffle-hog
  image: python:2.7-alpine
  commands:
      - apk add --no-cache git
      - echo $DRONE_SOURCE_BRANCH
      - echo $DRONE_REPO
      - cd moe-truffleHog
      - git branch
      -	pip install -r requirements.txt
      - python truffleHog/truffleHog.py --regex --rules rules.json --max_depth 1 --branch $DRONE_SOURCE_BRANCH "https://github.com/$DRONE_REPO.git" --entropy true 
      - echo "No tokens Found"
  when:
    trigger:
    - pull_request
