pipeline:

  github-status:
    api_key:
      from_secret: API_KEY
    when:
      event: pull_request
    image: jmccann/drone-github-status:0.1
    context: paras jain
  
  github-status-2:
    api_key:
      from_secret: API_KEY
    when:
      event: pull_request
    image: jmccann/drone-github-status:0.1
    context: paras jain 2 
    
  Truffle-hog clone:
    image: docker:git
    context: paras jain 3
    when:
      event: pull_request

