pipeline:
  github-status:
    api_key:
      from_secret: API_KEY
    when:
      event: pull_request
    image: jmccann/drone-github-status:0.1
    context: paras jain
    
  Truffle-hog clone:
    image: docker:git
    commands:    
     - git clone https://github.com/moengage/moe-truffleHog.git --branch dev
    when:
      event: pull_request
    context: paras jain 2

