---


kind: pipeline
type: docker
name: Lint/test check and Trufflehog
    
steps:

- name : Change github status
  image: python:2.7-alpine
  api_key:
    from_secret: API_KEY
  commands:
    - curl -X POST -H "Authorization: token "$API_KEY -H "Content-Type: application/json" -d "{\n  "state": "success",\n  "target_url": "https://example.com/build/status",\n  "description": "The build succeeded!",\n  "context": "continuous-integration/jenkins"\n}" "https://api.github.com/repos/ParasJain-dev/git_hook_test/statuses/c319f18d9e8f012ea0ba1bbcb7ede8dbe3cad3ef" 
  when:
    trigger:
    - pull_request
    
- name : Truffle-hog clone  
  image: docker:git
  commands:    
     - git clone https://github.com/moengage/moe-truffleHog.git --branch dev
  when:
    trigger:
    - pull_request
    
- name: Run truffle-hog
  image: python:2.7-alpine
  commands:
      - apk add --no-cache git
      - echo $DRONE_SOURCE_BRANCH
      - echo $DRONE_REPO
      - cd moe-truffleHog
      - git branch
      -	pip install -r requirements.txt
      - python truffleHog/truffleHog.py --regex --rules rules.json --max_depth 1 --branch $DRONE_SOURCE_BRANCH "https://github.com/$DRONE_REPO.git" --entropy true 
      - echo "No tokens Found"
  when:
    trigger:
    - pull_request
